//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osu.Game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("osu.Game.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background source.
        /// </summary>
        internal static string BackgroundSource {
            get {
                return ResourceManager.GetString("BackgroundSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change the way osu! behaves.
        /// </summary>
        internal static string ChangeBehavior {
            get {
                return ResourceManager.GetString("ChangeBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder location....
        /// </summary>
        internal static string ChangeFolder {
            get {
                return ResourceManager.GetString("ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface voices.
        /// </summary>
        internal static string InterfaceVoices {
            get {
                return ResourceManager.GetString("InterfaceVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro sequence.
        /// </summary>
        internal static string IntroSequence {
            get {
                return ResourceManager.GetString("IntroSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization menu.
        /// </summary>
        internal static string LocalizationMenu {
            get {
                return ResourceManager.GetString("LocalizationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer metadata in original language.
        /// </summary>
        internal static string metaPref {
            get {
                return ResourceManager.GetString("metaPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu! music theme.
        /// </summary>
        internal static string MusicTheme {
            get {
                return ResourceManager.GetString("MusicTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get up-to-date on community happenings.
        /// </summary>
        internal static string newsUpdate {
            get {
                return ResourceManager.GetString("newsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open osu! folder.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu!direct.
        /// </summary>
        internal static string osudirect {
            get {
                return ResourceManager.GetString("osudirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osu!editor.
        /// </summary>
        internal static string osueditor {
            get {
                return ResourceManager.GetString("osueditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release stream.
        /// </summary>
        internal static string ReleaseStream {
            get {
                return ResourceManager.GetString("ReleaseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer.
        /// </summary>
        internal static string Renderer {
            get {
                return ResourceManager.GetString("Renderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to default.
        /// </summary>
        internal static string RevertToDefault {
            get {
                return ResourceManager.GetString("RevertToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type to search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal backgrounds.
        /// </summary>
        internal static string SeasonalBackgrounds {
            get {
                return ResourceManager.GetString("SeasonalBackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
    }
}
